### ISSUE TITLE
Syntax errors in .tp2 files

### ISSUE THREAD

**Issue by elisimpson** [Transflux24/NPC-Bodies#2]
Leaving this information from a thread in Beamdog forums (https://forums.beamdog.com/discussion/68547/npc-bodies-a-death-and-resurrection-overhaul-for-eet)

Hello,

I've recently tried using the GitHub hosted version of the mod, but it did not work out of the box for me. In fact the .exe did not even like running at all, complaining of syntax errors in the .tp2 file.

I am not a modder, but I do code. By following up each error, and then modifying other files in analogy with other mods I have, I was able to get the mod to mostly work. I can confirm that it changed the revive price at temples, the CON penalty on resurrection now works. The resurrection also correctly requires the presence of the NPC body in inventory or else the character permanently dies. Finally, the CON penalty no longer instantly re-kills the NPC if they are on a CON breakpoint. All these things did not work in the mod files currently hosted.

The only remaining problem with my version is that NPCs do not drop bodies when the NPC dies inside an _indoor_ location (like a cave or a house). A body item correctly dropps only when killed outdoors. I can't seem to fix this. I am using the mod on a BG:EE game, with no SoD.

I am happy to provide my version if it's something the GitHub repo wants. I also just wanted to bring these issues to the attention of whomever may want to know. Given all the errors present, I think it's likely that the GitHub repo simply has an out of date version of the mod.

Let me close by saying the idea for this mod is really unique, and really appreciated for hardcore runs. I haven't seen this idea in any other mod I'm familiar with (that's not to say I know of a great many mods, but still). Temple revive and cleric spells badly need a tweak like this for hardcore, so I really appreciate the work that went into making this, thanks

**Comment by Transflux24** [comment]
Sorry, I completely forgot I started working on this. I'd appreciate your work if you still have it. I am currently trying to get an install set up before I decide to dedicate time back into this. I'll look into making this fully open to anyone to work on outside of myself. I thought I did as that was the plan. 

Thanks for all the info and work btw. Really appreciate it.

**Comment by Transflux24** [comment]
I am begining to work on this again and will have to refix most of these issues I fixed already but I decided to track each of these issues separately to organize myself better. I appreciate your detailed logging and am going to close this and use the broken up issues I opened.
